### ISSUE TITLE
Error when I try to import yaml

### ISSUE THREAD

**Issue by mflasquin** [microcks/microcks-cli#24]
Hi,
I have got an error when I try to import a yaml with the cli command :

`./bin/microcks-cli import 'api-contact-1.5.0-test.yaml:true' --microcksURL=http://localhost:8080/api/ --keycloakClientId=test --keycloakClientSecret=test`

result :

`panic: interface conversion: interface {} is nil, not string
goroutine 1 [running]:
github.com/microcks/microcks-cli/pkg/connectors.(*keycloakClient).ConnectAndGetToken(0xc0000a61e0)
	/Users/lbroudou/Development/go-workspace/src/github.com/microcks/microcks-cli/pkg/connectors/keycloak_client.go:88 +0x7a5
github.com/microcks/microcks-cli/cmd.(*importComamnd).Execute(0x63c380)
	/Users/lbroudou/Development/go-workspace/src/github.com/microcks/microcks-cli/cmd/import.go:92 +0x677
main.main()
	/Users/lbroudou/Development/go-workspace/src/github.com/microcks/microcks-cli/main.go:31 +0x103`

Thanks for your reply

**Comment by mflasquin** [comment]
This error occurs when we use bad credentials
